### PR TITLE
Regenerated expired test TLS certs

### PR DESCRIPTION
**Pull request by agrare**
Regenerate expired TLS certs by running `test/config/update_certs_k0s.rb`

### CODE REVIEW

**Comment by agrare** [comment]
@Fryguy recommend merging https://github.com/ManageIQ/kubeclient/pull/631 on red to fix the bundler version issue, then I'll rebase this one and it should go green.

**Comment by agrare** [comment]
Okay now only the 2.7 tests are failing which will be fixed by https://github.com/ManageIQ/kubeclient/pull/631

**Review by kbrock — APPROVED** [review]
thanks for the change

LGTM

**Comment by agrare** [comment]
Thanks @Fryguy !

**Pull request merged**
