### PR TITLE
support impersonation via auth_options and in kubectl config

### PR DESCRIPTION
**Pull request by grosser**
fixes https://github.com/abonas/kubeclient/issues/521

TODO: confirm it actually works (can check Monday)

### CODE REVIEW

**Comment by cben** [comment]
Code looks good, though I don't know much about the feature.
Have you confirmed it actually works?

**Comment by grosser** [comment]
I'm blocked by the ssl being broken in master :(
https://github.com/abonas/kubeclient/issues/525
in theory it should work since that's what I've been doing manually before (setting the headers)
if the ssl issue is hard to fix I can try rebasing this on 4.9 to do an end-to-end test ...

**Comment by cben** [comment]
Just a reminder SSL issues (that I'm aware of) have been fixed.

**Comment by DocX** [comment]
Hi @grosser I've updated your work to latest master and tested it works. I've run into the missing impersonation when working on our internal project. Getting the update makes it work.

I've made new PR here: https://github.com/ManageIQ/kubeclient/pull/600 but feel free to update this PR if you think you would loose the credit :)

**Comment by grosser** [comment]
the less my name is in git blame the better :D

**Pull request closed without merging**
